CREATE TABLE PRODUCTOS (
    ID_PRODUCTO      NUMBER(10)      CONSTRAINT PK_PRODUCTOS PRIMARY KEY,
    NOMBRE           VARCHAR2(100)   CONSTRAINT NN_PROD_NOM NOT NULL,
    STOCK_ACTUAL     NUMBER(10)      CONSTRAINT NN_PROD_STOCK NOT NULL,
    PRECIO_UNITARIO  NUMBER(10, 2)   CONSTRAINT NN_PROD_PRECIO NOT NULL,
    UNIDAD_MEDIDA    VARCHAR2(20));

-- Producto 1: Monitor
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE, STOCK_ACTUAL, PRECIO_UNITARIO, UNIDAD_MEDIDA)
VALUES (SEQ_PRODUCTOS.NEXTVAL, 'Monitor LED 27 Pulgadas', 75, 250.99, 'Unidad');

-- Producto 2: Teclado
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE, STOCK_ACTUAL, PRECIO_UNITARIO)
VALUES (SEQ_PRODUCTOS.NEXTVAL, 'Teclado Mecánico RGB', 150, 75.00);

-- Producto 3: Cable
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE, STOCK_ACTUAL, PRECIO_UNITARIO)
VALUES (SEQ_PRODUCTOS.NEXTVAL, 'Cable HDMI 2.0 (3m)', 500, 10.50);

-- Producto 4: Servidor (Ejemplo de un ítem con poco stock)
INSERT INTO PRODUCTOS (ID_PRODUCTO, NOMBRE, STOCK_ACTUAL, PRECIO_UNITARIO)
VALUES (SEQ_PRODUCTOS.NEXTVAL, 'Servidor Rackable Xeon', 5, 2500.00);