CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID_MOVIMIENTO      NUMBER(10)     CONSTRAINT PK_MOVIMIENTO PRIMARY KEY,
    ID_PRODUCTO        NUMBER(10)     CONSTRAINT NN_MOV_PROD NOT NULL,
    TIPO_MOVIMIENTO    VARCHAR2(10)   CONSTRAINT NN_MOV_TIPO NOT NULL,
    CANTIDAD           NUMBER(10)     CONSTRAINT NN_MOV_CANT NOT NULL,
    FECHA_MOVIMIENTO   DATE           DEFAULT SYSDATE,

    CONSTRAINT FK_MOV_PRODUCTO
        FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTOS(ID_PRODUCTO));